### ISSUE TITLE
Install AlchemyCat

### ISSUE THREAD

**Issue by J-Lam0** [HAL-42/FMA-WSSS#10]
How to install alchemy_cat , it does't have setup.py.

**Comment by HAL-42** [comment]
The alchemy_cat is still in develop. You can use alchemy_cat in the following three ways:
1. **[RECOMMENDED]** Download our pre-packaged conda environment from [HERE](https://pan.baidu.com/s/1jLHxyW5Hwv9YBmusazGGxg?pwd=2333), which includes a pre-installed version of alchemy_cat that is compatible with the project.
2. Clone [alchemy_cat ](https://github.com/HAL-42/AlchemyCat) and add it to your `sys.path`.
3. Use the setup.py script as follows:
```
from setuptools import setup, find_packages

setup(
        name='alchemy_cat',
        version='0.0.0',
        description='This is a test of the setup',
        author='HAL_42',
        author_email='hal_42@zju.edu.cn',
        url='https://github.com/HAL-42/AlchemyCat',
        packages=find_packages(),
        package_data = {
            '': ['*.md'],
        },
        zip_safe=True,
)
```

**Comment by Devin-Pi** [comment]
Hi, thanks for your wonderful work.

When I try to use the 'alchemy_cat', I have encountered the following problem. I would appreciate it if  you can help me solve this problem. Thank you!

Traceback (most recent call last):
  File "/workspaces/env/test.py", line 1, in <module>
    import alchemy_cat.py_tools.config.open_cfg as open_cfg
  File "/workspaces/env/alchemy_cat/__init__.py", line 11, in <module>
    from .acplot.shuffle_ch import CHW2HWC, HWC2CHW, RGB2BGR, BGR2RGB
  File "/workspaces/env/alchemy_cat/acplot/__init__.py", line 11, in <module>
    from .figure_wall import *
  File "/workspaces/env/alchemy_cat/acplot/figure_wall.py", line 18, in <module>
    from alchemy_cat.acplot.utils import stack_figs
  File "/workspaces/env/alchemy_cat/acplot/utils.py", line 15, in <module>
    from alchemy_cat.data.plugins.augers import pad_img_label
  File "/workspaces/env/alchemy_cat/data/__init__.py", line 11, in <module>
    from alchemy_cat.data.dataset import *
  File "/workspaces/env/alchemy_cat/data/dataset.py", line 19, in <module>
    from alchemy_cat.alg import accumulate
  File "/workspaces/env/alchemy_cat/alg/__init__.py", line 12, in <module>
    from alchemy_cat.alg.utils import *
  File "/workspaces/env/alchemy_cat/alg/utils.py", line 15, in <module>
    from alchemy_cat.py_tools import is_int, is_float, totuple
  File "/workspaces/env/alchemy_cat/py_tools/__init__.py", line 23, in <module>
    from alchemy_cat.py_tools.param_tuner import *
  File "/workspaces/env/alchemy_cat/py_tools/param_tuner/__init__.py", line 12, in <module>
    from alchemy_cat.py_tools.param_tuner.cfg2tune_runner import *
  File "/workspaces/env/alchemy_cat/py_tools/param_tuner/cfg2tune_runner.py", line 32, in <module>
    class Cfg2TuneRunner(object):
  File "/workspaces/env/alchemy_cat/py_tools/param_tuner/cfg2tune_runner.py", line 37, in Cfg2TuneRunner
    work_fn: Callable[[tuple[int, tuple[Config, str, str]]], ...]=None):
  File "/usr/lib/python3.10/typing.py", line 1206, in __getitem__
    return self.__getitem_inner__(params)
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1212, in __getitem_inner__
    result = _type_check(result, msg)
  File "/usr/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[args, result]: result must be a type. Got Ellipsis.

Look forward to your reply!

**Comment by HAL-42** [comment]
The current version of alchemy_cat needs Python >= 3.11
It is RECOMMENDED to download our pre-packaged conda environment from [HERE](https://pan.baidu.com/s/1jLHxyW5Hwv9YBmusazGGxg?pwd=2333), which includes a pre-installed version of alchemy_cat that is compatible with the project. Additionally, all dependencies required to run the project have been packaged within it.
